name: Deploy articles

on:
  push:
    branches:
      - gh

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm install
      - name: Deploy the project
        run: npm run deploy
