name: Merge articles

on:
  push:
    branches:
      - articles

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge articles -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: articles
          target_branch: main
          github_token: ${{ secrets.LONGREAD_TOKEN }}

